development: &non_production_settings
  site_url: http://localhost:3000/
  site_name: Hearsay
  admin_email: ryan.macinnes@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.thisishearsay.com
  site_name: Hearsay
  admin_email: ryan.macinnes@gmail.com  
  
production:
  site_url: http://www.thisishearsay.com
  site_name: Hearsay
  admin_email: ryan.macinnes@gmail.com
